# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_radar_interp_c', [dirname(__file__)])
        except ImportError:
            import _radar_interp_c
            return _radar_interp_c
        if fp is not None:
            try:
                _mod = imp.load_module('_radar_interp_c', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _radar_interp_c = swig_import_helper()
    del swig_import_helper
else:
    import _radar_interp_c
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def get_all_radar_pts(*args):
  return _radar_interp_c.get_all_radar_pts(*args)
get_all_radar_pts = _radar_interp_c.get_all_radar_pts

def binary_search(*args):
  return _radar_interp_c.binary_search(*args)
binary_search = _radar_interp_c.binary_search

def trilinear_interp(*args):
  return _radar_interp_c.trilinear_interp(*args)
trilinear_interp = _radar_interp_c.trilinear_interp
# This file is compatible with both classic and new-style classes.


